### ISSUE TITLE
Site needs a key

### ISSUE THREAD

**Issue by Ajedi32** [scottjehl/CSS-Download-Tests#9]
Why is the test for Opera 11 with `nonsense` green, even though it says "Downloaded" just like every other browser? The table could use a legend or key illustrating what the "correct" behavior should be for each browser and query, versus what it actually is.

**Comment by markusdrake** [comment]
I too can't make sense of the page. I got nothing from it. Do browsers download style sheets that would not apply?

**Comment by scottjehl** [comment]
thanks - fixed now. There's no variation in the results. It was just a broad test to verify that all those browsers download any css file.
